id: PDF0F4E80
initial_creation_type: ocr
source_metadata:
  volumes:
    2e4447f606444ae782f78e978bd49180:
      base_file: v015.txt
      image_group_id: I1PD95860
      title: ལེའུ་བཅོ་བརྒྱད་པའི་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1453
      volume_number: 15
