id: PDF0F4E80
initial_creation_type: ocr
source_metadata:
  volumes:
    6b27d56e5da546ef9fb57ece3522983c:
      base_file: v015.txt
      image_group_id: I1PD95860
      title: ལེའུ་བཅོ་བརྒྱད་པའི་རྒྱ་ཆེར་འགྲེལ་པ།
      total_pages: 1453
      volume_number: 15
